#! /bin/sh


INTERNAL_MONITOR="LVDS-1"
EXTERNAL_MONITOR_1="DP-3" #el 144
# on first load setup default workspaces
if [[ "$1" = 0 ]]; then
  if [[ $(xrandr -q | grep "${EXTERNAL_MONITOR_1} connected") ]]; then
    
    xrandr --output LVDS-1 --mode 1366x768 --rotate normal --output DP-3 --primary --mode 1920x1080 --rate 120 --rotate normal --right-of LVDS-1 
    bspc monitor "$EXTERNAL_MONITOR_1" -d 1 2 3 4 5
    bspc monitor "$INTERNAL_MONITOR" -d 6 7 8 9 10
    bspc wm -O "$EXTERNAL_MONITOR_1" "$INTERNAL_MONITOR"
  else
    bspc monitor "$INTERNAL_MONITOR" -d 1 2 3 4 5 6 7 8 9 10
  fi
fi 

EXTERNAL_MONITOR_2="VGA-1" 
if [[ "$1" = 0 ]]; then
  if [[ $(xrandr -q | grep "${EXTERNAL_MONITOR_2} connected") ]]; then

    xrandr --output LVDS-1 --mode 1366x768 --rotate normal --output VGA-1 --primary --mode 1360x768 --rate 60.02 --rotate normal --right-of LVDS-1
    bspc monitor "$EXTERNAL_MONITOR_2" -d 1 2 3 4 5
    bspc monitor "$INTERNAL_MONITOR" -d 6 7 8 9 10
    bspc wm -O "$EXTERNAL_MONITOR_2" "$INTERNAL_MONITOR"
  else
    bspc monitor "$INTERNAL_MONITOR" -d 1 2 3 4 5 6 7 8 9 10
  fi
fi 


pgrep -x sxhkd > /dev/null || sxhkd &

# bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         1
bspc config window_gap          6

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

#Startup
sxhkd &
picom --config $HOME/.config/picom/picom.conf &
nitrogen --restore &
dunst &
polybar &
bash ~/.config/polybar/launch.sh --shapes


xset -dpms
xset s off
